### PR TITLE
Don't include packages with forbidden control chars in repodata + some warning fixes

### PR DESCRIPTION
**Pull request by kontura**
As discussed in https://github.com/rpm-software-management/createrepo_c/issues/104 this PR ensures that packages with forbidden control chars are not included in repodata and appropriate warning is generated. Also when `--error-exit-val` is used and such a package is encountered return value is set to 2 as with other errors.

The third commit addresses compiler warnings when cmake is ran with -DCMAKE_BUILD_TYPE:STRING=DEBUG. Removing various unused code, fixing some incompatible types, initialization and so on.

### CODE REVIEW

**Comment by sergiomb2** [comment]
IMO     ` g_set_error(err, CREATEREPO_C_ERROR, CRE_XMLDATA,
                    "Forbidden control chars found (ASCII values <32 except 9, 10 and 13)."); `

should print pkg , for us know where this happens , or give any sort of clue how and where this happens

**Comment by ppisar** [comment]
A caller to cr_xml_dump() knows the package name. Or did you mean pointing to the bad byte in the package's textual metadata? The precise location would be great. But we will need to add a new function because cr_Package_contains_forbidden_control_chars() is missing an argument for returning the message and the function is listed in public header files.

**Comment by sergiomb2** [comment]
I mean the text around the bad character

**Comment by ppisar** [comment]
Thanks for the clarification. I recorded the request as issue #424.

**Comment by sergiomb2** [comment]
I propose this PR:  https://github.com/rpm-software-management/createrepo_c/pull/425

**Pull request merged**
