### PR TITLE
Fix rpm build script

### PR DESCRIPTION
**Pull request by InHavk**
Reported as #436 

Some small fixes of generating rpm packages

### CODE REVIEW

**Review by kontura — CHANGES_REQUESTED** [review]
Can you drop the `spec` file changes?
We keep this `spec` in sync with fedora downstream createrepo_c `spec` files and this would break our workflow. We are using the Github releases and those are `tar.gz`.

I would rather you update to `make_tarball.sh`.

**Comment by InHavk** [comment]
Sorry for long waiting, I've lost notification.

Problem there not only with format of archive. That part is easy to fix without touching spec.

Source tar named as a `%{name}-%{version}.tar.gz` in spec and `version` is hardcoded also there. It means, that spec always will wait `createrepo_c-1.1.4.tar.gz` with `createrepo_c-1.1.4` directory inside.

So, there is two ways:
1 - We can ignore `refs` as a version and `make_tarball.sh` always will make tar only with version that exact same as in spec. For instance, `make_tarball.sh branchname` will use `branchname` as source of code, but have `createrepo_c-1.1.4.tar.gz` in result.
2 - Add in spec some variable like `GITREV` with condition like `if GITREV exist - use it as version, instead use hardcoded version`. It shouldn't break building rpm in any other situation, if that variable hasn't used.

**Comment by kontura** [comment]
I would find the condition is spec file less confusing so I prefer the second approach.

**Review by kontura — APPROVED** [review]
I am sorry I didn't realize there will be a conflict and I bumped the version.
Can you please rebase?

Otherwise it looks good.

**Comment by InHavk** [comment]
Yeah, no problem. Rebased

**Comment by kontura** [comment]
Thank you

**Pull request merged**
