### PR TITLE
Add reboot_suggested to UpdateRecord (RhBug:1772466)

### PR DESCRIPTION
**Pull request by kontura**
I have also extended existing unit tests with this new field.

https://bugzilla.redhat.com/show_bug.cgi?id=1772466

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@kontura Could you also add one for `restart_suggested`? The Pulp guys were asking about it a couple of weeks ago...

**Comment by kontura** [comment]
@Conan-Kudo yea sure, I think they want it on the packages from pkglists right? As opposed to this `reboot_suggested` which is directly on UpdateRecord.

**Comment by Conan-Kudo** [comment]
@kontura it's an updateinfo property... https://en.opensuse.org/openSUSE:Standards_Rpm_Metadata_UpdateInfo#restart_suggested

It's the same level as `reboot_suggested`, I think.

**Comment by Conan-Kudo** [comment]
@kontura Both `reboot_suggested` and `restart_suggested` are in the pkg level in updateinfo...

**Comment by kontura** [comment]
@Conan-Kudo yes but this PR added `reboot_suggested` also to UpdateRecord as requested in the referenced bz, so `reboot_suggested` can now be twice in the updateinfo. 
Ok I will add `restart_suggested` to pkgs.

**Comment by Conan-Kudo** [comment]
@kontura excellent, thanks. I'm not sure why `reboot_suggested` needs to be at the top level updaterecord, since dnf won't parse that, but meh.

**Comment by Conan-Kudo** [comment]
@kontura Once that PR is made and I merge it, I'll cut the next release of createrepo_c.

**Comment by kontura** [comment]
@Conan-Kudo ok, I think I should make the PR tomorrow.

**Pull request merged**
