### PR TITLE
tags for old suse versions

### PR DESCRIPTION
**Pull request by M0ses**

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@M0ses Could you guard this out with some kind of switch? I don't think it would make sense for this tag logic to be activated by default. Not to mention, you've explicitly noted this is for legacy stuff, so I would hesitate to suggest that it's something you'd want to have stick around forever.

**Comment by Conan-Kudo** [comment]
Looks good to me :+1: 

@Tojaj: What do you think about it?

**Comment by Tojaj** [comment]
@Conan-Kudo Agree!

@M0ses Thank you!

**Comment by Tojaj** [comment]
Btw. I've just pushed two patches that update output printed when `--version` is used and when version is printed during verbose logging (`--verbose`).

Now there is a list of enabled compile-time features, e.g.:

    Version: 0.10.0 (Features: DeltaRPM LegacyWeakdeps )

**Comment by M0ses** [comment]
cool, the features list will be a great help for debugging.

**Pull request merged**
