### PR TITLE
add the supports of vcs tag

### PR DESCRIPTION
**Pull request by janncker**
Signed-off-by: Hasan Wan hasan.wan@intel.com

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@Tojaj If I might make a suggestion? These extended attribute tags should probably be behind a switch/config option so that they aren't on by default. I definitely agree that the repodata should be as minimal as possible, but @kad's point that Debian does include it in their metadata (for better or worse) means that other people may in the future find it useful. 

I'm not entirely sure why the Tizen Project needs this information in the metadata for the repository, but provided that it's not a "default on" feature, I don't see any reason why it can't be there.

**Comment by kad** [comment]
In Tizen it was used for very specific reason - to be able to track from binary RPM distribution back to origins of source, as VCS tag includes full URL and commit id of sources used to generate package (both actual sources and corresponding meta-data, with help of support git-buildpackage).

**Comment by Conan-Kudo** [comment]
@Tojaj Could this be brought in if the generation of this was triggered by a flag rather than default behavior? I'd rather not see the metadata get bigger (I would rather see it slimmed down and support xml.xz format to be even smaller), but Tizen is using this tag, so I don't see a good reason for it not to be in there, again, as long as it isn't pulled in by default.

**Comment by kad** [comment]
Scenario where it would be included only if additional switch specified to createrepo as described by @Conan-Kudo would be good enough solution in my opinion.

**Comment by Conan-Kudo** [comment]
@janncker Do you think you could implement what I suggested earlier for your pull request? It would probably make it much more palatable to merge in.

**Comment by janncker** [comment]
@Conan-Kudo I can help on this even I'm not on this project now.  But, after a quick search on the latest branch, there's no mechanism to make a tag optional. @Tojaj do you have plan to support tags as optioinal? Or global cmd option is acceptable?

**Comment by Conan-Kudo** [comment]
@janncker I suspect that a global command option that would enable the functionality (default disabled) would be fine.

**Comment by j-mracek** [comment]
I am sorry but I am closing the PR as an inactive.

**Pull request closed without merging**
