### PR TITLE
Deltarpm to drpm, documentation and some build warnings

### PR DESCRIPTION
**Pull request by kontura**
- Minor fixes in docs.
- Regenerated manpages with `utils/gen_manpage.sh` to keep it updated.
- Fixed couple of warnings when compiled with `-DCMAKE_BUILD_TYPE:STRING=DEBUG`.
- Switching from deltarpm to drpm library, also reduces dependencies.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Has anyone actually verified that drpm's creation functionality is good?

**Comment by dmach** [comment]
I have manually tested that `createrepo_c --deltas --oldpackagesdir=<PATH> .` produces deltas that have reasonable size, but nothing beyond that.
-> looks good to me

@Conan-Kudo if you're fine with the code quality, feel free to merge it.

**Comment by Conan-Kudo** [comment]
@dmach Do they work in terms of reconstituting them using `applydeltarpm`?

**Comment by dmach** [comment]
@Conan-Kudo good point; let me verify that before we proceed

**Comment by dmach** [comment]
@Conan-Kudo applydeltarpm was able to reconstruct an identical copy of the original file.

**Comment by Conan-Kudo** [comment]
Good enough for me, merging.

**Comment by kontura** [comment]
I was testing it with simple test packages while developing this and it worked fine however after your comment I tried it out with some real packages and it doesn't seem to work. I will look into it. Thank you.

**Comment by Conan-Kudo** [comment]
Well, it's good I haven't cut a release yet. Fix it up and send another PR. :)

**Comment by kontura** [comment]
Yes I think the problem is actually with the drpm's creation functionality as you mentioned, it seems to work only for some packages.

**Pull request merged**
