### PR TITLE
Update logging function for  standard mode

### PR DESCRIPTION
**Pull request by zdtsw**

### CODE REVIEW

**Comment by dmach** [comment]
@zdtsw could you rebase your PR please?
Once you do it, I'll re-test and merge it.

**Comment by zdtsw** [comment]
did a rebase, seems quite has been changed, but only need MESSAGE than DEBUG if it is a standard mode. hope it is working

**Comment by dmach** [comment]
Github still complains about "This branch cannot be rebased due to conflicts"
I've reviewed your changes and there seemed to be related changes in the past that were conflicting with yours and that have covered some of the changes you had in your commit already.
I ended up cherry-picking your last commit on top of master and put it here:
https://github.com/dmach/createrepo_c/tree/zdtsw
Could you review I did it right and I didn't forget anything?

If you're fine with content of my branch, you can either force-push it in your branch to refresh this PR or I can close this PR and push the commit manually.

**Comment by zdtsw** [comment]
Yeah I think the cherry-pick is the one I want,Basically my change is to make the standard one as MESSAGE not DEBUG which spit out too much infor. 
Maybe it is easy for you to push the change manually, my force push probably might end up into something strange for git.

**Comment by dmach** [comment]
Ok, I'll push the patch by myself and close this PR.
Thanks for the patch and for your patience (we're cleaning up our PR backlog, hoping to be more responsive from now on)

**Comment by dmach** [comment]
Merged: https://github.com/rpm-software-management/createrepo_c/commit/4c2f4f48f259c19219d4d640884c5df7a7d4fc5e

**Pull request closed without merging**
